### ISSUE TITLE
but，this is more ,difficult to use than GSON

### ISSUE THREAD

**Issue by bravekingzhang** [yigit/jsonapi-parser#2]

**Comment by yigit** [comment]
here is the rationale:
http://www.birbit.com/jsonapi-is-a-blessing-for-offline-ready-apps/

Why do you think it is difficult? More code ?

**Comment by bravekingzhang** [comment]
yes ,more code than before,and more difficult to understand.

anyway,Thanks a lot ,It's time for me to learn a new skill.
